# Generated by Django 3.1.5 on 2021-01-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1611765533.4292405),
        ),
    ]
