# Generated by Django 3.1.5 on 2021-02-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0002_auto_20210209_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1612814754.3510144),
        ),
    ]
