# Generated by Django 3.1.5 on 2021-02-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0003_auto_20210209_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1612874773.1101637),
        ),
    ]
