# Generated by Django 3.1.5 on 2021-02-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0004_auto_20210209_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1613119123.6575024),
        ),
    ]
