# Generated by Django 3.1.5 on 2021-02-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0006_auto_20210214_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1613318460.412256),
        ),
    ]
