# Generated by Django 3.1.5 on 2021-02-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0008_auto_20210214_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1613319107.7318656),
        ),
    ]
