# Generated by Django 3.1.5 on 2021-02-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0009_auto_20210214_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1613319202.9891021),
        ),
    ]
