# Generated by Django 3.1.5 on 2021-02-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0014_auto_20210217_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1613542180.218691),
        ),
    ]
