# Generated by Django 3.1.5 on 2021-02-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0015_auto_20210217_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1613542392.533528),
        ),
    ]
