# Generated by Django 3.1.5 on 2021-02-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0018_auto_20210217_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1613551753.1413343),
        ),
    ]
