# Generated by Django 3.1.5 on 2021-02-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0019_auto_20210217_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1614010384.8629572),
        ),
    ]
