# Generated by Django 3.1.5 on 2021-02-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0020_auto_20210222_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1614010479.944476),
        ),
    ]
