# Generated by Django 3.1.5 on 2021-02-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0021_auto_20210222_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1614092789.1064498),
        ),
    ]
