# Generated by Django 3.1.5 on 2021-02-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0022_auto_20210223_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1614092798.9495268),
        ),
    ]
