# Generated by Django 3.1.5 on 2021-02-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0025_auto_20210224_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1614112000.9895525),
        ),
    ]
