# Generated by Django 3.1.5 on 2021-02-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0026_auto_20210224_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1614295930.685296),
        ),
    ]
