# Generated by Django 3.1.5 on 2021-02-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0030_auto_20210226_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1614337281.3013074),
        ),
    ]
