# Generated by Django 3.1.5 on 2021-02-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0031_auto_20210226_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1614407599.8351798),
        ),
    ]
