# Generated by Django 3.1.5 on 2021-02-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0032_auto_20210227_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1614425811.8411684),
        ),
    ]
