# Generated by Django 3.1.5 on 2021-02-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0033_auto_20210227_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1614426996.1456294),
        ),
    ]
