# Generated by Django 3.1.5 on 2021-03-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0040_auto_20210302_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1614625897.9589064),
        ),
    ]
