# Generated by Django 3.1.5 on 2021-03-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0042_auto_20210302_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1614626748.8484845),
        ),
    ]
