# Generated by Django 3.1.5 on 2021-03-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0003_auto_20210127_2208'),
        ('All_Users', '0044_auto_20210302_0058'),
    ]

    operations = [
    ]
