# Generated by Django 3.1.5 on 2021-03-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0045_merge_20210302_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1616908756.0589576),
        ),
    ]
