# Generated by Django 3.1.5 on 2021-03-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0046_auto_20210328_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1616908801.425828),
        ),
    ]
