# Generated by Django 3.1.5 on 2021-03-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0047_auto_20210328_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1616961012.0353532),
        ),
    ]
