# Generated by Django 3.1.5 on 2021-03-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_Users', '0048_auto_20210329_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.FloatField(default=1617015878.8798232),
        ),
    ]
