# Generated by Django 3.1.5 on 2021-02-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notsure',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notsure',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
