# Generated by Django 3.1.5 on 2021-02-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0002_auto_20210209_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Description', models.TextField()),
                ('Test_Type', models.CharField(max_length=50)),
                ('Pre_Test_Information', models.CharField(max_length=500)),
                ('Test_Components', models.CharField(max_length=500)),
                ('Report_Delivery', models.CharField(blank=True, max_length=500, null=True)),
                ('Price', models.FloatField()),
                ('Discount_Price', models.FloatField()),
                ('Method', models.TextField()),
            ],
        ),
    ]
