# Generated by Django 3.1.5 on 2021-02-14 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0005_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthpackage',
            name='conditions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lab.condition'),
        ),
        migrations.AddField(
            model_name='tests',
            name='conditions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lab.condition'),
        ),
    ]
