# Generated by Django 3.1.5 on 2021-02-14 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0006_auto_20210214_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthpackage',
            name='conditions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab.condition'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='conditions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab.condition'),
        ),
    ]
