# Generated by Django 3.1.5 on 2021-02-22 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Lab', '0007_auto_20210214_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Ordered', models.BooleanField(default=False)),
                ('Package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab.healthpackage')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab.tests')),
            ],
        ),
    ]
