# Generated by Django 3.1.5 on 2021-02-23 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Lab', '0009_auto_20210222_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ordered_Date', models.DateTimeField()),
                ('Ordered', models.BooleanField(default=False)),
                ('total_amount', models.FloatField(blank=True, default=0, null=True)),
                ('new', models.BooleanField(blank=True, default=True, null=True)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Tests', models.ManyToManyField(to='Lab.Cart')),
            ],
        ),
    ]
