# Generated by Django 3.1.5 on 2021-02-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0010_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Packages',
            field=models.ManyToManyField(related_name='Packages_Field', to='Lab.Cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Tests',
            field=models.ManyToManyField(related_name='Tests_Field', to='Lab.Cart'),
        ),
    ]
