# Generated by Django 3.1.5 on 2021-02-23 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0011_auto_20210223_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Cart'},
        ),
        migrations.AlterModelOptions(
            name='tests',
            options={'verbose_name_plural': 'Tests'},
        ),
    ]
