# Generated by Django 3.1.5 on 2021-02-23 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0012_auto_20210224_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Date',
        ),
    ]
