# Generated by Django 3.1.5 on 2021-02-25 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Lab', '0013_remove_cart_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=500)),
                ('PinCode', models.IntegerField()),
                ('Charges', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=500, null=True)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('Landmark', models.TextField(blank=True, null=True)),
                ('Extra', models.TextField(blank=True, null=True)),
                ('Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('default', models.BooleanField(default=False)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
