# Generated by Django 3.1.5 on 2021-02-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0015_address_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='secondary_address',
            field=models.BooleanField(default=False),
        ),
    ]
