# Generated by Django 3.1.5 on 2021-02-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0018_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_status',
            field=models.CharField(blank=True, choices=[('Incart', 'Incart'), ('Processing', 'Processing'), ('Arrived', 'Arrived'), ('Collected', 'Collected'), ('Result Out', 'Result Out')], max_length=50, null=True),
        ),
    ]
