# Generated by Django 3.1.5 on 2021-03-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0020_auto_20210227_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='when',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
