# Generated by Django 3.1.5 on 2021-03-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0021_cart_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='when',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
