# Generated by Django 3.1.5 on 2021-03-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Phone', models.CharField(max_length=15)),
                ('Prescription', models.FileField(upload_to='Prescriptions')),
                ('Address', models.TextField()),
                ('Other_Detail', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
