# Generated by Django 3.1.5 on 2021-03-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicines',
            name='Prescription',
        ),
        migrations.AddField(
            model_name='medicines',
            name='Prescription_File',
            field=models.FileField(blank=True, null=True, upload_to='Prescriptions'),
        ),
        migrations.AddField(
            model_name='medicines',
            name='Prescription_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Prescriptions'),
        ),
    ]
