# Generated by Django 3.1.5 on 2021-02-17 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=50)),
                ('Booked', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctors.category')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('Qualification', models.CharField(max_length=500)),
                ('Overall_Exp', models.CharField(max_length=500)),
                ('Description', models.TextField()),
                ('Fee', models.FloatField(blank=True, null=True)),
                ('Profile_pic', models.ImageField(blank=True, null=True, upload_to='Doctor_Profile')),
                ('Days', models.ManyToManyField(blank=True, to='Doctors.Days')),
                ('Field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctors.category')),
                ('SubField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctors.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='days',
            name='Doctor_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctors.doctor'),
        ),
        migrations.CreateModel(
            name='AllBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=50)),
                ('Fee', models.FloatField()),
                ('paid', models.BooleanField(default=False)),
                ('Allot_Time', models.DateTimeField(blank=True, null=True)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctors.doctor')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
