# Generated by Django 3.1.5 on 2021-02-17 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Days', 'verbose_name_plural': 'Days'},
        ),
    ]
