# Generated by Django 3.1.5 on 2021-02-02 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Doctor_Profile'),
        ),
        migrations.CreateModel(
            name='AllBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=50)),
                ('Fee', models.FloatField()),
                ('paid', models.BooleanField(default=False)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctors.doctor')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
