# Generated by Django 3.1.5 on 2021-02-17 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0002_auto_20210217_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='days',
            options={'verbose_name': 'Days', 'verbose_name_plural': 'Days'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
    ]
