# Generated by Django 3.1.5 on 2021-02-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0003_auto_20210217_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='Day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thrusday', 'Thrusday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=50),
        ),
    ]
