# Generated by Django 3.1.5 on 2021-02-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0004_auto_20210217_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='Days',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Thrusday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Wednesday',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Days',
        ),
    ]
