# Generated by Django 3.1.5 on 2021-02-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0006_auto_20210227_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='allbooking',
            name='Phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
