# Generated by Django 3.1.5 on 2021-03-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0007_allbooking_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Avaliable_From',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Avaliable_Upto',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
