# Generated by Django 3.1.5 on 2021-03-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0002_auto_20210202_1836'),
        ('Doctors', '0009_auto_20210302_0055'),
    ]

    operations = [
    ]
